logging:
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
spring:
  rabbitmq:
    host: 192.168.59.222
    port: 5672
    username: root
    password: root
    virtual-host: /
#    listener:
#      simple:
#        prefetch: 1
